// IDistributedApplicationBuilder.java - GENERATED CODE - DO NOT EDIT

package aspire;

import java.util.*;
import java.util.function.*;

/** Wrapper for Aspire.Hosting/Aspire.Hosting.IDistributedApplicationBuilder. */
public class IDistributedApplicationBuilder extends HandleWrapperBase {
    IDistributedApplicationBuilder(Handle handle, AspireClient client) {
        super(handle, client);
    }

    public ContainerRegistryResource addContainerRegistry(String name, String endpoint, String repository) {
        return addContainerRegistry(name, AspireUnion.of(endpoint), AspireUnion.of(repository));
    }

    public ContainerRegistryResource addContainerRegistry(String name, String endpoint, ParameterResource repository) {
        return addContainerRegistry(name, AspireUnion.of(endpoint), AspireUnion.of(repository));
    }

    public ContainerRegistryResource addContainerRegistry(String name, ParameterResource endpoint, String repository) {
        return addContainerRegistry(name, AspireUnion.of(endpoint), AspireUnion.of(repository));
    }

    public ContainerRegistryResource addContainerRegistry(String name, ParameterResource endpoint, ParameterResource repository) {
        return addContainerRegistry(name, AspireUnion.of(endpoint), AspireUnion.of(repository));
    }

    public ContainerRegistryResource addContainerRegistry(String name, AspireUnion endpoint) {
        return addContainerRegistry(name, endpoint, (AspireUnion) null);
    }

    /** Adds a container registry resource */
    public ContainerRegistryResource addContainerRegistry(String name, AspireUnion endpoint, AspireUnion repository) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        reqArgs.put("name", AspireClient.serializeValue(name));
        reqArgs.put("endpoint", AspireClient.serializeValue(endpoint));
        if (repository != null) {
            reqArgs.put("repository", AspireClient.serializeValue(repository));
        }
        var result = getClient().invokeCapability("Aspire.Hosting/addContainerRegistry", reqArgs);
        return (ContainerRegistryResource) result;
    }

    public ContainerResource addContainer(String name, String image) {
        return addContainer(name, AspireUnion.of(image));
    }

    public ContainerResource addContainer(String name, AddContainerOptions image) {
        return addContainer(name, AspireUnion.of(image));
    }

    /** Adds a container resource to the application. */
    public ContainerResource addContainer(String name, AspireUnion image) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        reqArgs.put("name", AspireClient.serializeValue(name));
        reqArgs.put("image", AspireClient.serializeValue(image));
        var result = getClient().invokeCapability("Aspire.Hosting/addContainer", reqArgs);
        return (ContainerResource) result;
    }

    /** Adds a Dockerfile to the application model that can be treated like a container resource. */
    public ContainerResource addDockerfile(String name, String contextPath, AddDockerfileOptions options) {
        var dockerfilePath = options == null ? null : options.getDockerfilePath();
        var stage = options == null ? null : options.getStage();
        return addDockerfileImpl(name, contextPath, dockerfilePath, stage);
    }

    public ContainerResource addDockerfile(String name, String contextPath) {
        return addDockerfile(name, contextPath, null);
    }

    /** Adds a Dockerfile to the application model that can be treated like a container resource. */
    private ContainerResource addDockerfileImpl(String name, String contextPath, String dockerfilePath, String stage) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        reqArgs.put("name", AspireClient.serializeValue(name));
        reqArgs.put("contextPath", AspireClient.serializeValue(contextPath));
        if (dockerfilePath != null) {
            reqArgs.put("dockerfilePath", AspireClient.serializeValue(dockerfilePath));
        }
        if (stage != null) {
            reqArgs.put("stage", AspireClient.serializeValue(stage));
        }
        var result = getClient().invokeCapability("Aspire.Hosting/addDockerfile", reqArgs);
        return (ContainerResource) result;
    }

    public ContainerResource addDockerfileFactory(String name, String contextPath, AspireFunc1<DockerfileFactoryContext, String> dockerfileFactory) {
        return addDockerfileFactory(name, contextPath, dockerfileFactory, null);
    }

    /** Adds a Dockerfile to the application model that can be treated like a container resource, with the Dockerfile content generated by an asynchronous factory function. */
    public ContainerResource addDockerfileFactory(String name, String contextPath, AspireFunc1<DockerfileFactoryContext, String> dockerfileFactory, String stage) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        reqArgs.put("name", AspireClient.serializeValue(name));
        reqArgs.put("contextPath", AspireClient.serializeValue(contextPath));
        var dockerfileFactoryId = getClient().registerCallback(args -> {
            var arg = (DockerfileFactoryContext) args[0];
            return AspireClient.awaitValue(dockerfileFactory.invoke(arg));
        });
        if (dockerfileFactoryId != null) {
            reqArgs.put("dockerfileFactory", dockerfileFactoryId);
        }
        if (stage != null) {
            reqArgs.put("stage", AspireClient.serializeValue(stage));
        }
        var result = getClient().invokeCapability("Aspire.Hosting/addDockerfileFactory", reqArgs);
        return (ContainerResource) result;
    }

    public ContainerResource addDockerfileBuilder(String name, String contextPath, AspireAction1<DockerfileBuilderCallbackContext> callback) {
        return addDockerfileBuilder(name, contextPath, callback, null);
    }

    /** Adds a container resource built from a programmatically generated Dockerfile */
    public ContainerResource addDockerfileBuilder(String name, String contextPath, AspireAction1<DockerfileBuilderCallbackContext> callback, String stage) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        reqArgs.put("name", AspireClient.serializeValue(name));
        reqArgs.put("contextPath", AspireClient.serializeValue(contextPath));
        var callbackId = getClient().registerCallback(args -> {
            var arg = (DockerfileBuilderCallbackContext) args[0];
            callback.invoke(arg);
            return null;
        });
        if (callbackId != null) {
            reqArgs.put("callback", callbackId);
        }
        if (stage != null) {
            reqArgs.put("stage", AspireClient.serializeValue(stage));
        }
        var result = getClient().invokeCapability("Aspire.Hosting/addDockerfileBuilder", reqArgs);
        return (ContainerResource) result;
    }

    /** Adds a .NET tool resource to the application model. */
    public DotnetToolResource addDotnetTool(String name, String packageId) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        reqArgs.put("name", AspireClient.serializeValue(name));
        reqArgs.put("packageId", AspireClient.serializeValue(packageId));
        var result = getClient().invokeCapability("Aspire.Hosting/addDotnetTool", reqArgs);
        return (DotnetToolResource) result;
    }

    /** Adds an executable resource to the application model. */
    public ExecutableResource addExecutable(String name, String command, String workingDirectory, String[] args) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        reqArgs.put("name", AspireClient.serializeValue(name));
        reqArgs.put("command", AspireClient.serializeValue(command));
        reqArgs.put("workingDirectory", AspireClient.serializeValue(workingDirectory));
        reqArgs.put("args", AspireClient.serializeValue(args));
        var result = getClient().invokeCapability("Aspire.Hosting/addExecutable", reqArgs);
        return (ExecutableResource) result;
    }

    public ExternalServiceResource addExternalService(String name, String url) {
        return addExternalService(name, AspireUnion.of(url));
    }

    public ExternalServiceResource addExternalService(String name, ParameterResource url) {
        return addExternalService(name, AspireUnion.of(url));
    }

    /** Adds an external service resource */
    public ExternalServiceResource addExternalService(String name, AspireUnion url) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        reqArgs.put("name", AspireClient.serializeValue(name));
        reqArgs.put("url", AspireClient.serializeValue(url));
        var result = getClient().invokeCapability("Aspire.Hosting/addExternalService", reqArgs);
        return (ExternalServiceResource) result;
    }

    /** Directory of the project where the app host is located. Defaults to the content root if there's no project. */
    public String appHostDirectory() {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("context", AspireClient.serializeValue(getHandle()));
        var result = getClient().invokeCapability("Aspire.Hosting/IDistributedApplicationBuilder.appHostDirectory", reqArgs);
        return (String) result;
    }

    /** Gets the Environment property */
    public IHostEnvironment environment() {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("context", AspireClient.serializeValue(getHandle()));
        var result = getClient().invokeCapability("Aspire.Hosting/IDistributedApplicationBuilder.environment", reqArgs);
        return (IHostEnvironment) result;
    }

    /** Eventing infrastructure for AppHost lifecycle. */
    public IDistributedApplicationEventing eventing() {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("context", AspireClient.serializeValue(getHandle()));
        var result = getClient().invokeCapability("Aspire.Hosting/IDistributedApplicationBuilder.eventing", reqArgs);
        return (IDistributedApplicationEventing) result;
    }

    /** Execution context for this invocation of the AppHost. */
    public DistributedApplicationExecutionContext executionContext() {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("context", AspireClient.serializeValue(getHandle()));
        var result = getClient().invokeCapability("Aspire.Hosting/IDistributedApplicationBuilder.executionContext", reqArgs);
        return (DistributedApplicationExecutionContext) result;
    }

    /** Gets the deployment pipeline for this distributed application. */
    public IDistributedApplicationPipeline pipeline() {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("context", AspireClient.serializeValue(getHandle()));
        var result = getClient().invokeCapability("Aspire.Hosting/IDistributedApplicationBuilder.pipeline", reqArgs);
        return (IDistributedApplicationPipeline) result;
    }

    /** Gets the service for managing user secrets. */
    public IUserSecretsManager userSecretsManager() {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("context", AspireClient.serializeValue(getHandle()));
        var result = getClient().invokeCapability("Aspire.Hosting/IDistributedApplicationBuilder.userSecretsManager", reqArgs);
        return (IUserSecretsManager) result;
    }

    /** Builds the distributed application */
    public DistributedApplication build() {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("context", AspireClient.serializeValue(getHandle()));
        var result = getClient().invokeCapability("Aspire.Hosting/build", reqArgs);
        return (DistributedApplication) result;
    }

    /** Adds a parameter resource */
    public ParameterResource addParameter(String name, AddParameterOptions options) {
        var value = options == null ? null : options.getValue();
        var publishValueAsDefault = options == null ? null : options.getPublishValueAsDefault();
        var secret = options == null ? null : options.getSecret();
        return addParameterImpl(name, value, publishValueAsDefault, secret);
    }

    public ParameterResource addParameter(String name) {
        return addParameter(name, null);
    }

    /** Adds a parameter resource */
    private ParameterResource addParameterImpl(String name, String value, Boolean publishValueAsDefault, Boolean secret) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        reqArgs.put("name", AspireClient.serializeValue(name));
        if (value != null) {
            reqArgs.put("value", AspireClient.serializeValue(value));
        }
        if (publishValueAsDefault != null) {
            reqArgs.put("publishValueAsDefault", AspireClient.serializeValue(publishValueAsDefault));
        }
        if (secret != null) {
            reqArgs.put("secret", AspireClient.serializeValue(secret));
        }
        var result = getClient().invokeCapability("Aspire.Hosting/addParameter", reqArgs);
        return (ParameterResource) result;
    }

    public ParameterResource addParameterFromConfiguration(String name, String configurationKey) {
        return addParameterFromConfiguration(name, configurationKey, null);
    }

    /** Adds a parameter resource to the application, with a value coming from configuration. */
    public ParameterResource addParameterFromConfiguration(String name, String configurationKey, Boolean secret) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        reqArgs.put("name", AspireClient.serializeValue(name));
        reqArgs.put("configurationKey", AspireClient.serializeValue(configurationKey));
        if (secret != null) {
            reqArgs.put("secret", AspireClient.serializeValue(secret));
        }
        var result = getClient().invokeCapability("Aspire.Hosting/addParameterFromConfiguration", reqArgs);
        return (ParameterResource) result;
    }

    /** Adds a parameter with a generated default value */
    public ParameterResource addParameterWithGeneratedValue(String name, GenerateParameterDefault value, AddParameterWithGeneratedValueOptions options) {
        var secret = options == null ? null : options.getSecret();
        var persist = options == null ? null : options.getPersist();
        return addParameterWithGeneratedValueImpl(name, value, secret, persist);
    }

    public ParameterResource addParameterWithGeneratedValue(String name, GenerateParameterDefault value) {
        return addParameterWithGeneratedValue(name, value, null);
    }

    /** Adds a parameter with a generated default value */
    private ParameterResource addParameterWithGeneratedValueImpl(String name, GenerateParameterDefault value, Boolean secret, Boolean persist) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        reqArgs.put("name", AspireClient.serializeValue(name));
        reqArgs.put("value", AspireClient.serializeValue(value));
        if (secret != null) {
            reqArgs.put("secret", AspireClient.serializeValue(secret));
        }
        if (persist != null) {
            reqArgs.put("persist", AspireClient.serializeValue(persist));
        }
        var result = getClient().invokeCapability("Aspire.Hosting/addParameterWithGeneratedValue", reqArgs);
        return (ParameterResource) result;
    }

    public IResourceWithConnectionString addConnectionString(String name, String environmentVariableNameOrExpression) {
        return addConnectionString(name, AspireUnion.of(environmentVariableNameOrExpression));
    }

    public IResourceWithConnectionString addConnectionString(String name, ReferenceExpression environmentVariableNameOrExpression) {
        return addConnectionString(name, AspireUnion.of(environmentVariableNameOrExpression));
    }

    public IResourceWithConnectionString addConnectionString(String name) {
        return addConnectionString(name, (AspireUnion) null);
    }

    /** Adds a connection string resource */
    public IResourceWithConnectionString addConnectionString(String name, AspireUnion environmentVariableNameOrExpression) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        reqArgs.put("name", AspireClient.serializeValue(name));
        if (environmentVariableNameOrExpression != null) {
            reqArgs.put("environmentVariableNameOrExpression", AspireClient.serializeValue(environmentVariableNameOrExpression));
        }
        var result = getClient().invokeCapability("Aspire.Hosting/addConnectionString", reqArgs);
        return (IResourceWithConnectionString) result;
    }

    public ProjectResource addProject(String name, String projectPath, String launchProfileOrOptions) {
        return addProject(name, projectPath, AspireUnion.of(launchProfileOrOptions));
    }

    public ProjectResource addProject(String name, String projectPath, ProjectResourceOptions launchProfileOrOptions) {
        return addProject(name, projectPath, AspireUnion.of(launchProfileOrOptions));
    }

    public ProjectResource addProject(String name, String projectPath) {
        return addProject(name, projectPath, (AspireUnion) null);
    }

    /** Adds a .NET project resource */
    public ProjectResource addProject(String name, String projectPath, AspireUnion launchProfileOrOptions) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        reqArgs.put("name", AspireClient.serializeValue(name));
        reqArgs.put("projectPath", AspireClient.serializeValue(projectPath));
        if (launchProfileOrOptions != null) {
            reqArgs.put("launchProfileOrOptions", AspireClient.serializeValue(launchProfileOrOptions));
        }
        var result = getClient().invokeCapability("Aspire.Hosting/addProject", reqArgs);
        return (ProjectResource) result;
    }

    public CSharpAppResource addCSharpApp(String name, String path) {
        return addCSharpApp(name, path, null);
    }

    /** Adds a C# application resource */
    public CSharpAppResource addCSharpApp(String name, String path, ProjectResourceOptions options) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        reqArgs.put("name", AspireClient.serializeValue(name));
        reqArgs.put("path", AspireClient.serializeValue(path));
        if (options != null) {
            reqArgs.put("options", AspireClient.serializeValue(options));
        }
        var result = getClient().invokeCapability("Aspire.Hosting/addCSharpApp", reqArgs);
        return (CSharpAppResource) result;
    }

    /** Gets the application configuration. */
    public IConfiguration getConfiguration() {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        var result = getClient().invokeCapability("Aspire.Hosting/getConfiguration", reqArgs);
        return (IConfiguration) result;
    }

    /** Subscribes to the BeforeStart event, which fires before the application starts. */
    public DistributedApplicationEventSubscription subscribeBeforeStart(AspireAction1<BeforeStartEvent> callback) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        var callbackId = getClient().registerCallback(args -> {
            var arg = (BeforeStartEvent) args[0];
            callback.invoke(arg);
            return null;
        });
        if (callbackId != null) {
            reqArgs.put("callback", callbackId);
        }
        var result = getClient().invokeCapability("Aspire.Hosting/subscribeBeforeStart", reqArgs);
        return (DistributedApplicationEventSubscription) result;
    }

    /** Subscribes to the BeforePublish event, which fires before the application is published. */
    public DistributedApplicationEventSubscription subscribeBeforePublish(AspireAction1<BeforePublishEvent> callback) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        var callbackId = getClient().registerCallback(args -> {
            var arg = (BeforePublishEvent) args[0];
            callback.invoke(arg);
            return null;
        });
        if (callbackId != null) {
            reqArgs.put("callback", callbackId);
        }
        var result = getClient().invokeCapability("Aspire.Hosting/subscribeBeforePublish", reqArgs);
        return (DistributedApplicationEventSubscription) result;
    }

    /** Subscribes to the AfterPublish event, which fires after the application is published. */
    public DistributedApplicationEventSubscription subscribeAfterPublish(AspireAction1<AfterPublishEvent> callback) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        var callbackId = getClient().registerCallback(args -> {
            var arg = (AfterPublishEvent) args[0];
            callback.invoke(arg);
            return null;
        });
        if (callbackId != null) {
            reqArgs.put("callback", callbackId);
        }
        var result = getClient().invokeCapability("Aspire.Hosting/subscribeAfterPublish", reqArgs);
        return (DistributedApplicationEventSubscription) result;
    }

    /** Subscribes to the AfterResourcesCreated event, which fires after all resources are created. */
    public DistributedApplicationEventSubscription subscribeAfterResourcesCreated(AspireAction1<AfterResourcesCreatedEvent> callback) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        var callbackId = getClient().registerCallback(args -> {
            var arg = (AfterResourcesCreatedEvent) args[0];
            callback.invoke(arg);
            return null;
        });
        if (callbackId != null) {
            reqArgs.put("callback", callbackId);
        }
        var result = getClient().invokeCapability("Aspire.Hosting/subscribeAfterResourcesCreated", reqArgs);
        return (DistributedApplicationEventSubscription) result;
    }

    /** Adds an ATS-friendly eventing subscriber callback to the distributed-application builder. */
    public void addEventingSubscriber(AspireAction1<EventingSubscriberRegistrationContext> subscribe) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        var subscribeId = getClient().registerCallback(args -> {
            var arg = (EventingSubscriberRegistrationContext) args[0];
            subscribe.invoke(arg);
            return null;
        });
        if (subscribeId != null) {
            reqArgs.put("subscribe", subscribeId);
        }
        getClient().invokeCapability("Aspire.Hosting/addEventingSubscriber", reqArgs);
    }

    /** Attempts to add an ATS-friendly eventing subscriber callback to the distributed-application builder. */
    public void tryAddEventingSubscriber(AspireAction1<EventingSubscriberRegistrationContext> subscribe) {
        Map<String, Object> reqArgs = new HashMap<>();
        reqArgs.put("builder", AspireClient.serializeValue(getHandle()));
        var subscribeId = getClient().registerCallback(args -> {
            var arg = (EventingSubscriberRegistrationContext) args[0];
            subscribe.invoke(arg);
            return null;
        });
        if (subscribeId != null) {
            reqArgs.put("subscribe", subscribeId);
        }
        getClient().invokeCapability("Aspire.Hosting/tryAddEventingSubscriber", reqArgs);
    }

}
